### ISSUE TITLE
What makes this "lock free" exactly?

### ISSUE THREAD

**Issue by ghost** [munogu/maildir-queue#1]
Your README says:

**Stores messages using Maildir format to avoid using file locks.**

I'm trying to understand precisely how file locks are avoided.  What is it that makes using the Maildir format "lock free"?

thanks!

**Comment by eymengunay** [comment]
Hello @bootrino ,

You can find an in-depth explanation about maildir format and how it avoids file locks simply on its wikipedia article:

https://en.m.wikipedia.org/wiki/Maildir

To summarize:
Instead of creating lock files it relies on rename operations hence it delegates the file locking to the operating system. 
For instance a new item gets added to “new” folder waiting to be processed. Once the worker starts processing this new item it gets moved to “cur” directory. 
The constant moving of files (or in our specific case queue items) between three folders is what makes it lock file.

I hope this explains it a little bit better.
